services:
  # üêò PostgreSQL (Compartilhado)
  postgres:
    image: postgres:15
    container_name: zenndi-postgres
    restart: always
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_MULTIPLE_DATABASES: "zenndi_core,zenndi_auth,zenndi_scanner" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-multiple-dbs.sh:/docker-entrypoint-initdb.d/init-multiple-dbs.sh
    networks:
      - zenndi-network
    ports:
     - "127.0.0.1:5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev"]
      interval: 10s
      timeout: 5s
      retries: 5    

  # üöÄ Redis (Compartilhado)
  redis:
    image: redis:7-alpine
    container_name: zenndi-redis
    restart: always
    # Habilita persist√™ncia e define senha
    command: >
      sh -c "redis-server --appendonly yes
      ${REDIS_PASSWORD:+--requirepass ${REDIS_PASSWORD}}"

    volumes:
      - redis_data:/data
    networks:
      - zenndi-network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ${REDIS_PASSWORD:+-a $REDIS_PASSWORD} ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    # ports:
    # - "6379:6379"  # Adicionado mapeamento de porta para acesso externo
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: zenndi-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: dev
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks: [zenndi-network]
    ports:
      - "127.0.0.1:15672:15672"
      - "127.0.0.1:5672:5672"  
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5 

  # üóÑÔ∏è MinIO (Storage S3)
  minio:
    image: minio/minio
    container_name: zenndi-minio
    restart: always
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: dev
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      # Apenas localhost (acess√≠vel via SSH Tunnel)
      - "127.0.0.1:9000:9000" # API
      - "127.0.0.1:9001:9001" # Console Web
    volumes:
      - minio_data:/data
    networks:
      - zenndi-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3    
 
volumes:
  postgres_data:
  redis_data:
  rabbitmq_data:
  minio_data:

networks:
  zenndi-network:
    external: true