services:
  # üåê NGINX (API Gateway)
  nginx:
    image: nginx:1.25-alpine
    container_name: zenndi-nginx
    restart: always
    ports:
      - "80:80"        # entrada principal da API
      # - "443:443"    # depois ativamos TLS
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
    networks:
      - zenndi-network

networks:
  zenndi-network:
    external: true